dev_addr: 127.0.0.1:9000
docs_dir: docs/src
edit_uri: "/tree/develop/docs/source"
repo_url: https://github.com/saxix/django-adminfilters
site_description: ""
site_dir: ./~build/docs
site_name: Documentation
site_url: https://github.com/saxix/django-adminfilters
strict: false


markdown_extensions:
  - admonition
  - pymdownx.magiclink
  - mdx_gh_links:
      user: saxix
      repo: django-adminfilters
  - markdown_include.include:
      base_path: .
  - attr_list
  - md_in_html


theme:
  name: "material"
  color_mode: auto
#  highlightjs: true
#  hljs_languages:
#    - yaml
#    - django
  user_color_mode_toggle: true
  features:
    - content.action.edit
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - header.autohidex
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
  extra:
    version:
      provider: mike
      alias: true
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: light blue
      media: "(prefers-color-scheme: light)"
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: light blue
      media: "(prefers-color-scheme: dark)"
      toggle:
        icon: material/weather-night
        name: Switch to light mode

plugins:
  - mkdocstrings:
      default_handler: python
  - awesome-pages
  - search
  - autolinks


watch:
  - docs/
  - src/
