# Generated by Django 5.2.8 on 2025-11-17 15:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("depot", "0003_alter_storedfilter_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="storedfilter",
            name="query_string",
            field=models.TextField(blank=True, default=""),
        ),
    ]
